/**
 * Vercel Function — bridges Node IncomingMessage/ServerResponse to the
 * TanStack Start SSR's Web `fetch(Request) -> Response` handler.
 *
 * The handler module is generated by `npm run build` into ../dist/server/server.js.
 * Vercel auto-bundles dist/ when an api/ function references it, so it ships
 * with the function output.
 */

import server from "../dist/server/server.js";

function nodeRequestToWebRequest(req) {
  const proto = req.headers["x-forwarded-proto"] ?? "https";
  const host = req.headers["x-forwarded-host"] ?? req.headers.host ?? "localhost";
  const url = `${proto}://${host}${req.url}`;

  const headers = new Headers();
  for (const [k, v] of Object.entries(req.headers)) {
    if (Array.isArray(v)) {
      for (const item of v) headers.append(k, item);
    } else if (typeof v === "string") {
      headers.set(k, v);
    }
  }

  const method = req.method ?? "GET";
  const init = { method, headers };
  if (method !== "GET" && method !== "HEAD") {
    init.body = req;
    init.duplex = "half";
  }
  return new Request(url, init);
}

async function writeWebResponseToNode(response, res) {
  res.statusCode = response.status;
  for (const [key, value] of response.headers) {
    res.setHeader(key, value);
  }
  if (!response.body) {
    res.end();
    return;
  }
  const reader = response.body.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    res.write(value);
  }
  res.end();
}

export default async function handler(req, res) {
  try {
    const request = nodeRequestToWebRequest(req);
    const response = await server.fetch(request, process.env, undefined);
    await writeWebResponseToNode(response, res);
  } catch (err) {
    console.error("[ssr]", err);
    if (!res.headersSent) {
      res.statusCode = 500;
      res.setHeader("content-type", "text/html; charset=utf-8");
    }
    res.end("<h1>Internal server error</h1>");
  }
}

export const config = {
  api: { bodyParser: false },
};
