/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublisherRouteImport } from './routes/publisher'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkerRouteImport } from './routes/dashboard/worker'
import { Route as DashboardRequesterRouteImport } from './routes/dashboard/requester'

const PublisherRoute = PublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkerRoute = DashboardWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequesterRoute = DashboardRequesterRouteImport.update({
  id: '/requester',
  path: '/requester',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/publisher': typeof PublisherRoute
  '/dashboard/requester': typeof DashboardRequesterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/publisher': typeof PublisherRoute
  '/dashboard/requester': typeof DashboardRequesterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/publisher': typeof PublisherRoute
  '/dashboard/requester': typeof DashboardRequesterRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/publisher'
    | '/dashboard/requester'
    | '/dashboard/worker'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/publisher'
    | '/dashboard/requester'
    | '/dashboard/worker'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/publisher'
    | '/dashboard/requester'
    | '/dashboard/worker'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublisherRoute: typeof PublisherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publisher': {
      id: '/publisher'
      path: '/publisher'
      fullPath: '/publisher'
      preLoaderRoute: typeof PublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/worker': {
      id: '/dashboard/worker'
      path: '/worker'
      fullPath: '/dashboard/worker'
      preLoaderRoute: typeof DashboardWorkerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requester': {
      id: '/dashboard/requester'
      path: '/requester'
      fullPath: '/dashboard/requester'
      preLoaderRoute: typeof DashboardRequesterRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardRequesterRoute: typeof DashboardRequesterRoute
  DashboardWorkerRoute: typeof DashboardWorkerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRequesterRoute: DashboardRequesterRoute,
  DashboardWorkerRoute: DashboardWorkerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PublisherRoute: PublisherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
